"""add api_key_ciphertext to agent_credentials

Revision ID: f0f13ff71128
Revises: f790c725a862
Create Date: 2026-09-27 13:06:03.281867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0f13ff71128'
down_revision: Union[str, Sequence[str], None] = 'f790c725a862'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_credentials', sa.Column('api_key_ciphertext', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_credentials', 'api_key_ciphertext')
    # ### end Alembic commands ###
