"""init schema

Revision ID: f790c725a862
Revises: 
Create Date: 2026-09-27 12:23:57.939395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f790c725a862'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE TYPE agent_visibility AS ENUM ('personal', 'team', 'to_be_published')")
    op.execute("CREATE TYPE agent_classification AS ENUM ('Internal', 'Confidential', 'Restricted')")
    op.execute("CREATE TYPE agent_stage AS ENUM ('PROMOTE', 'POC_DEV', 'TESTING', 'PILOT', 'PRODUCTION')")
    op.execute("CREATE TYPE model_access_kind AS ENUM ('requested', 'granted')")
    op.execute("CREATE TYPE publication_status AS ENUM ('pending', 'compliance_review', 'approved', 'published', 'rejected')")
    op.execute("CREATE TYPE registration_status AS ENUM ('pending', 'approved', 'rejected')")
    op.execute("CREATE TYPE credential_status AS ENUM ('active', 'revoked', 'rotated')")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('agent_name', sa.Text(), nullable=False),
    sa.Column('department', sa.Text(), nullable=False),
    sa.Column('owner_team', sa.Text(), nullable=False),
    sa.Column('intended_audience', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('visibility', postgresql.ENUM('personal', 'team', 'to_be_published', name='agent_visibility', create_type=False), nullable=False),
    sa.Column('expected_user_count_per_month', sa.Integer(), nullable=True),
    sa.Column('use_case_business_need', sa.Text(), nullable=True),
    sa.Column('classification', postgresql.ENUM('Internal', 'Confidential', 'Restricted', name='agent_classification', create_type=False), nullable=True),
    sa.Column('tier', sa.Text(), nullable=True),
    sa.Column('environment', sa.Text(), nullable=True),
    sa.Column('current_stage', postgresql.ENUM('PROMOTE', 'POC_DEV', 'TESTING', 'PILOT', 'PRODUCTION', name='agent_stage', create_type=False), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('agent_id')
    )
    op.create_table('agent_model_access',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.Text(), nullable=False),
    sa.Column('kind', postgresql.ENUM('requested', 'granted', name='model_access_kind', create_type=False), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_publications',
    sa.Column('publication_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'compliance_review', 'approved', 'published', 'rejected', name='publication_status', create_type=False), nullable=False),
    sa.Column('submitted_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('use_case', sa.Text(), nullable=True),
    sa.Column('raw_request', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('publication_id')
    )
    op.create_table('agent_registrations',
    sa.Column('registration_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'approved', 'rejected', name='registration_status', create_type=False), nullable=False),
    sa.Column('submitted_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('reviewed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.Text(), nullable=True),
    sa.Column('environment', sa.Text(), nullable=True),
    sa.Column('raw_request', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('registration_id')
    )
    op.create_table('audit_log',
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('method', sa.Text(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('actor', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('agent_credentials',
    sa.Column('credential_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('registration_id', sa.UUID(), nullable=True),
    sa.Column('api_key_hash', sa.Text(), nullable=False),
    sa.Column('api_key_last4', sa.Text(), nullable=False),
    sa.Column('status', postgresql.ENUM('active', 'revoked', 'rotated', name='credential_status', create_type=False), nullable=False),
    sa.Column('authentication_mode', sa.Text(), nullable=True),
    sa.Column('display_policy', sa.Text(), nullable=True),
    sa.Column('copy_requires_rbac', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_rotated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['registration_id'], ['agent_registrations.registration_id'], ),
    sa.PrimaryKeyConstraint('credential_id')
    )
    op.create_table('compliance_signoffs',
    sa.Column('signoff_id', sa.UUID(), nullable=False),
    sa.Column('publication_id', sa.UUID(), nullable=False),
    sa.Column('approver_name', sa.Text(), nullable=True),
    sa.Column('approver_role', sa.Text(), nullable=True),
    sa.Column('approval_rule', sa.Text(), nullable=True),
    sa.Column('evidence_pack', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('promotion_gate', sa.Text(), nullable=True),
    sa.Column('decision_status', sa.Text(), nullable=True),
    sa.Column('retained_evidence_complete', sa.Boolean(), nullable=True),
    sa.Column('final_review_package_attached', sa.Boolean(), nullable=True),
    sa.Column('compliance_approver_assigned', sa.Boolean(), nullable=True),
    sa.Column('decided_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['publication_id'], ['agent_publications.publication_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('signoff_id')
    )
    op.create_table('go_live_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('publication_id', sa.UUID(), nullable=False),
    sa.Column('marketplace_registry_status', sa.Text(), nullable=True),
    sa.Column('unified_chat_access', sa.Text(), nullable=True),
    sa.Column('telemetry_streaming', sa.Text(), nullable=True),
    sa.Column('monitoring', sa.Text(), nullable=True),
    sa.Column('production_environment', sa.Text(), nullable=True),
    sa.Column('activated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['publication_id'], ['agent_publications.publication_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('go_live_results')
    op.drop_table('compliance_signoffs')
    op.drop_table('agent_credentials')
    op.drop_table('audit_log')
    op.drop_table('agent_registrations')
    op.drop_table('agent_publications')
    op.drop_table('agent_model_access')
    op.drop_table('agents')
    # ### end Alembic commands ###
    op.execute("DROP TYPE credential_status")
    op.execute("DROP TYPE registration_status")
    op.execute("DROP TYPE publication_status")
    op.execute("DROP TYPE model_access_kind")
    op.execute("DROP TYPE agent_stage")
    op.execute("DROP TYPE agent_classification")
    op.execute("DROP TYPE agent_visibility")